package events

import (
	"testing"
)

func TestAutoGeneratedIDs(t *testing.T) {
	tests := []struct {
		name     string
		effect   interface{ Validate() error }
		getId    func() string
		expected string
	}{
		{
			name:     "Dialogue auto-generates readable ID",
			effect:   &EffectDialogue{Text: "Hello"},
			getId:    func() string { e := &EffectDialogue{Text: "Hello"}; e.Validate(); return e.DialogueId },
			expected: "dialogue-",
		},
		{
			name:     "Chatter auto-generates readable ID",
			effect:   &EffectChatter{EntityId: "player", DurationSeconds: 1, Message: "Hi"},
			getId:    func() string { e := &EffectChatter{EntityId: "player", DurationSeconds: 1, Message: "Hi"}; e.Validate(); return e.ChatterId },
			expected: "chatter-",
		},
		{
			name:     "Timer auto-generates readable ID",
			effect:   &EffectTimer{DurationSeconds: 5},
			getId:    func() string { e := &EffectTimer{DurationSeconds: 5}; e.Validate(); return e.TimerId },
			expected: "timer-",
		},
		{
			name:     "Fade auto-generates readable ID",
			effect:   &EffectFade{DurationSeconds: 2, Transitions: 1},
			getId:    func() string { e := &EffectFade{DurationSeconds: 2, Transitions: 1}; e.Validate(); return e.FadeId },
			expected: "fade-",
		},
		{
			name:     "Combat auto-generates readable ID",
			effect:   &EffectTriggerCombat{Background: "forest"},
			getId:    func() string { e := &EffectTriggerCombat{Background: "forest"}; e.Validate(); return e.CombatId },
			expected: "trigger-combat-",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			id := tt.getId()
			if len(id) == 0 {
				t.Errorf("Expected ID to be generated, got empty string")
			}
			if len(id) < len(tt.expected) {
				t.Errorf("Expected ID prefix %q, got %q", tt.expected, id)
			}
			prefix := id[:len(tt.expected)]
			if prefix != tt.expected {
				t.Errorf("Expected ID to start with %q, got %q", tt.expected, prefix)
			}
			t.Logf("Generated ID: %s", id)
		})
	}
}

func TestAutoGeneratedIDsAreSequential(t *testing.T) {
	e1 := &EffectDialogue{Text: "First"}
	e1.Validate()
	
	e2 := &EffectDialogue{Text: "Second"}
	e2.Validate()
	
	e3 := &EffectDialogue{Text: "Third"}
	e3.Validate()
	
	t.Logf("ID 1: %s", e1.DialogueId)
	t.Logf("ID 2: %s", e2.DialogueId)
	t.Logf("ID 3: %s", e3.DialogueId)
	
	if e1.DialogueId == e2.DialogueId || e2.DialogueId == e3.DialogueId {
		t.Error("Expected unique IDs for each effect")
	}
}

func TestManualIDsArePreserved(t *testing.T) {
	e := &EffectDialogue{
		DialogueId: "my-custom-id",
		Text:       "Hello",
	}
	
	err := e.Validate()
	if err != nil {
		t.Errorf("Validation failed: %v", err)
	}
	
	if e.DialogueId != "my-custom-id" {
		t.Errorf("Expected manual ID to be preserved, got %q", e.DialogueId)
	}
}
