save_id: default
character_name: Todd
animech:
    skill_set:
        "1": tackle
        "2": guard
        "3": ""
        "4": ""
    experience_points: 100
    upgrades:
        shield_level: 0
        sync_level: 0
    pending_experience: 50
    current_sync: 0
    current_shield: 0
loadouts: []
inventory: null
primortals:
    dummy:
        visibility: defeated
        research_points: 0
        last_seen: 2026-02-07T19:48:21.633819-05:00
        pending_research_points: 0
    toxmidge:
        visibility: defeated
        research_points: 5
        last_seen: 0001-01-01T00:00:00Z
        pending_research_points: 0
unlocked_skills:
    guard: {}
    jab: {}
    tackle: {}
globals:
    combat.training.opponent_attacks_while_player_defends: true
    combat.training.player_attacks_while_opponent_defends: true
    control_id: controlled_npc
    elythium: 0
    elythium_goal: 12
    intro.do_not_enter.attempts: ""
    player_id: tiled-16
    tiled-363: e5d2a3e3-fb71-4db2-8e39-3963cfa8249e
system_settings:
    lighting:
        lighting_composition: full
        lighting_mode: Blended
        bloom_mode: Blended
    combat:
        combat_speed: 1
    retro_frame:
        disable_pixel_grid: false
        override_retro_overlay: false
        scanline_darken: 0.015
        grid_darken_x: 0.05
        grid_darken_y: 0.05
        subpixel_tint: 0.05
    debugging:
        show_pathfinding_debugging: false
        game_time_speed: 3.384640459947183
    audio:
        muted: false
        master_volume: 1
    display:
        scale_mode: fixed
        fixed_scale: 3
        fullscreen: false
        virtual_gamepad: auto
        virtual_gamepad_opacity: 0.7443061440677967
        ui_scale: 0.5
