save_id: default
character_name: Todd
animech:
    skill_set:
        "1": tackle
        "2": guard
        "3": acid_string
        "4": ""
    experience_points: 0
    upgrades:
        shield_level: 2
        sync_level: 0
loadouts: []
inventory: null
primortals:
    "":
        visibility: defeated
        research_points: 0
        last_seen: 2026-02-08T14:11:33.247298-05:00
    dummy:
        visibility: defeated
        research_points: 0
        last_seen: 2026-02-07T19:48:21.633819-05:00
    toxmidge:
        visibility: defeated
        research_points: 6
        last_seen: 2026-02-08T14:04:32.440569-05:00
unlocked_skills:
    acid_string: {}
    guard: {}
    tackle: {}
globals:
    abilities.xenolog_access: true
    abilities.xenolog_primortals: true
    combat.training.opponent_attacks_while_player_defends: true
    combat.training.player_attacks_while_opponent_defends: true
    combat.training.player_status.poisoned: true
    control_id: controlled_npc
    elythium: 0
    elythium_goal: 12
    intro.control.elythium: false
    intro.training.5.xenolog: true
    intro.training.6.door: true
    intro.training.7.door: true
    intro.training.7.elythium.done: true
    intro.training.10.door: true
    intro.training.enter.listener: a6c5121c-6775-4322-a0ae-3b74da0e37a2
    player_id: tiled-16
    tiled-363: a6c5121c-6775-4322-a0ae-3b74da0e37a2
system_settings:
    lighting:
        lighting_composition: full
        lighting_mode: Blended
        bloom_mode: Blended
    combat:
        combat_speed: 1
    retro_frame:
        disable_pixel_grid: false
        scanline_darken: 0.015
        grid_darken_x: 0.05
        grid_darken_y: 0.05
        subpixel_tint: 0.05
    debugging:
        show_pathfinding_debugging: false
