package util

import (
	"fmt"
	"math/rand"
)

type StringList []string

func (s StringList) Random() string {
	return s[rand.Intn(len(s))]
}

func (s StringList) Randomf(args ...interface{}) string {
	return fmt.Sprintf(s.Random(), args...)
}

var OneOffDialogues = StringList{
	"Don't trust the company. Trust me. Actually, don't trust me either.",
	"You smell like off-world dust. Been exploring?",
	"Thanatek pays well, but at what cost?",
	"You're not from around here, are you?",
	"Some specimens bite back. Hard.",
	"They say the void whispers. I say it shouts.",
	"I miss solid ground. Space is overrated.",
	"Got any Primortal scans? I collect them.",
	"Ever seen a gas creature suffocate? Disturbing stuff.",
	"The AI talks to itself sometimes. Just ignore it.",
	"One day, this whole place will be dust.",
	"Thanatek owns the research. We just borrow it.",
	"Aether storms scrambled my last drone. Good luck.",
	"That trader over there? Don't believe a word.",
	"I used to be a researcher. Now I just survive.",
	"The last guy who questioned the company vanished. Weird.",
	"Scan logs don't lie. People do.",
	"I once saw a rock move. Not roll. Move.",
	"You're here for the Primortals, aren't you?",
	"Sometimes, the specimens study us too.",
	"If it glows, it's either valuable or deadly.",
	"This planet's got a bad history. Tread carefully.",
	"I swear the specimens are learning.",
	"Careful - Thanatek listens even when you think they aren't.",
	"Nobody makes it off-world without a price.",
	"Watch your back. And your front. And above.",
	"Ever wonder if we're the real experiments?",
	"The gas clouds here? Not just weather.",
	"Thanatek said this site was abandoned. They lied.",
	"Got any spare Aether? My scanner's fried.",
	"I had a Primortal once. Until it had me.",
	"There's something big moving under the surface.",
	"No one knows who built that structure. No one.",
	"Your Animech looks... damaged. Been through some things?",
	"This place is quiet. Too quiet.",
	"If you find a corpse, I was never here.",
	"Some traders sell real data. Others sell traps.",
	"Thanatek promised safety. They didn't promise survival.",
	"You're not with Thanatek, are you? Good.",
	"The first rule? Never touch the glowing stuff.",
	"Some Primortals resist capture. Those are the interesting ones.",
	"I heard a scream from the caves last night.",
	"I lost my drone out there. Not going back.",
	"The ground pulses at night. Don't ask why.",
	"Find anything good? Or just trouble?",
	"This isn't the first time they've sent someone.",
	"Think fast! Just kidding, just wanted to see you flinch.",
	"People go missing out here. Don't be one of them.",
	"The stars look different every time I check.",
	"I don't need a scanner. I just listen.",
	"See that structure? It wasn't there yesterday.",
	"You ever imprint something you shouldn't have?",
	"Some doors shouldn't be opened. Some already have been.",
	"If the signal stops, run.",
	"The company says this world is safe. It's not.",
	"Your Animech's resonance is off. You feeling okay?",
	"The traders? Half of them are Thanatek spies.",
	"The sky shouldn't move like that, should it?",
	"If you hear a hum, leave immediately.",
	"This place changes people. Sometimes permanently.",
	"Some Primortals remember their past lives. Some don't.",
	"You ever see a Primortal escape its imprint?",
	"You're collecting data? Who's collecting data on you?",
	"Thanatek's files are never complete. That's on purpose.",
	"Your shadow's moving wrong. Just saying.",
	"Don't let them scan you. That's how it starts.",
	"Stay in the light. Trust me.",
	"The void takes. But sometimes, it gives back.",
	"We don't dream here. Or maybe we do, and forget.",
	"Something in the caves is watching. I feel it.",
	"Your Animech hums a little different than mine.",
	"Stay off the red sand. Just trust me.",
	"I saw an Animech move on its own last night.",
	"The company says this is a research site. It's a graveyard.",
	"If you vanish, I'll take your gear. Nothing personal.",
	"You trust your scanner? I don't.",
	"Don't stare at the anomalies. They stare back.",
	"Some data is better left unlogged.",
	"The wind isn't supposed to whisper like that.",
	"I swear I saw my reflection blink.",
	"Got any spare power cores? I lost mine. Again.",
	"They sent an expedition here years ago. Where are they?",
	"The specimens learn. So should we.",
	"Feel that vibration? That's not normal.",
	"Somebody's jamming the signals. No idea who.",
	"You hear static? That means something's nearby.",
	"Nothing here is natural. Nothing.",
	"Your footprints vanish too quickly. Weird, right?",
	"Thanatek can't control what they don't understand.",
	"This planet's unstable. And not just geologically.",
	"Ever notice the ruins are older than the fossils?",
	"Whatever was here before? It didn't leave willingly.",
	"The scanners always glitch in the same spot.",
	"You're either lucky or doomed. Haven't decided which.",
	"The fog moves against the wind. That's...odd.",
	"Everything here is temporary. Even us.",
	"You get used to the isolation. Or you don't.",
	"Some traders have maps. Others just have lies.",
	"I wouldn't scan that if I were you.",
	"Your Animech's sync is slipping. Be careful.",
	"There's an old wreck nearby. No survivors, just echoes.",
	"Not all Primortals want to be captured.",
	"They say the first explorers heard music in the dark.",
	"Something's feeding on the power grid. Something big.",
	"You feel that? Like something watching? It's real.",
}

var EmptyChestMessages = StringList{
	"Empty. Just like my patience.",
	"Not a thing. Not even dust.",
	"Nope. Nada. Zilch. Total disappointment.",
	"Looks like someone beat you to it.",
	"You found... nothing. Congrats?",
	"If there was something here, it's gone now.",
	"Bone dry. Like a desert with less charm.",
	"Deader than deep space.",
	"As empty as corporate promises.",
	"Hollow. Void. A whole lotta nothing.",
	"If disappointment had a shape, this would be it.",
	"Checked twice. Still empty.",
	"A black hole would be jealous of this emptiness.",
	"Not even a scrap left behind.",
	"Vacant. Barren. A whole lot of wasted time.",
	"If nothingness had a home, this would be it.",
	"It's emptier than my last paycheck.",
	"Someone cleaned this out before you got here.",
	"Nothing but echoes and regret.",
	"A container filled with pure, uncut disappointment.",
}

var SingularItemFoundMessageFormats = StringList{
	"You found %s. Lucky you.",
	"Jackpot! %s is now yours.",
	"Scavenging success! Picked up %s.",
	"%s? Could be useful.",
	"Nice. %s just for you.",
	"You grab %s. Hope it's worth it.",
	"%s? Not bad, not bad.",
	"Dibs! You pocket %s.",
	"Something shiny... it's %s!",
	"Congratulations! You are now the owner of %s.",
	"You pick up %s. It hums slightly.",
	"Another day, another %s.",
	"%s? Wonder what it's doing here.",
	"The %s looks intact. Taking it.",
	"Someone left %s behind. Their loss.",
	"You found %s. Probably still functional.",
	"%s, just lying around? Suspicious.",
	"Score! A perfectly good %s.",
	"Unexpected, but welcome. %s acquired.",
	"%s. Hope it doesn't explode.",
}
